//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_wpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chambers
    {
        public int Id_chambers { get; set; }
        public string Count_of_space { get; set; }
    }
}
