//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_wpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id_patient { get; set; }
        public string Name { get; set; }
        public string Second_Name { get; set; }
        public string Age { get; set; }
        public string Status { get; set; }
        public string Start_Treatment { get; set; }
        public string End_Treatment { get; set; }
        public Nullable<int> Id_Treatment { get; set; }
        public Nullable<int> Id_Doctor { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Type_of_Treatment Type_of_Treatment { get; set; }
    }
}
