//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_wpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int Id_Treatment { get; set; }
        public string Treatment_Time { get; set; }
        public int Type_Treatment { get; set; }
    
        public virtual Type_of_Treatment Type_of_Treatment { get; set; }
    }
}
